<?php

/*
 *  User: dirty
 *  Email: shijie1991@gmail.com
 */

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AdminMenuTableSeeder extends Seeder
{
    /**
     * Auto generated seed file.
     */
    public function run()
    {
        \DB::table('admin_menu')->delete();

        \DB::table('admin_menu')->insert([
            0 => [
                'id'         => 1,
                'parent_id'  => 0,
                'order'      => 1,
                'title'      => '主页',
                'icon'       => 'feather icon-bar-chart-2',
                'uri'        => '/',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-29 07:48:07',
                'updated_at' => '2020-06-30 04:39:55',
            ],
            1 => [
                'id'         => 2,
                'parent_id'  => 0,
                'order'      => 26,
                'title'      => '系统管理',
                'icon'       => 'feather icon-settings',
                'uri'        => null,
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-29 07:48:07',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            2 => [
                'id'         => 3,
                'parent_id'  => 2,
                'order'      => 27,
                'title'      => '管理员',
                'icon'       => '',
                'uri'        => 'auth/users',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-29 07:48:07',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            3 => [
                'id'         => 4,
                'parent_id'  => 2,
                'order'      => 28,
                'title'      => '角色',
                'icon'       => '',
                'uri'        => 'auth/roles',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-29 07:48:07',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            4 => [
                'id'         => 5,
                'parent_id'  => 2,
                'order'      => 29,
                'title'      => '权限',
                'icon'       => '',
                'uri'        => 'auth/permissions',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-29 07:48:07',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            5 => [
                'id'         => 6,
                'parent_id'  => 2,
                'order'      => 30,
                'title'      => '菜单',
                'icon'       => '',
                'uri'        => 'auth/menu',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-29 07:48:07',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            6 => [
                'id'         => 8,
                'parent_id'  => 2,
                'order'      => 31,
                'title'      => '违禁词管理',
                'icon'       => null,
                'uri'        => 'sensitive_word',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-30 04:44:01',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            7 => [
                'id'         => 9,
                'parent_id'  => 0,
                'order'      => 19,
                'title'      => '广告中心',
                'icon'       => 'fa-buysellads',
                'uri'        => null,
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-30 04:50:02',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            8 => [
                'id'         => 10,
                'parent_id'  => 9,
                'order'      => 21,
                'title'      => '广告管理',
                'icon'       => null,
                'uri'        => '/ad',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-30 07:13:25',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            9 => [
                'id'         => 11,
                'parent_id'  => 9,
                'order'      => 20,
                'title'      => '广告位管理',
                'icon'       => null,
                'uri'        => '/ad_category',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-30 07:14:04',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            10 => [
                'id'         => 12,
                'parent_id'  => 0,
                'order'      => 16,
                'title'      => '文章中心',
                'icon'       => 'fa-book',
                'uri'        => null,
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-30 08:06:51',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            11 => [
                'id'         => 13,
                'parent_id'  => 12,
                'order'      => 17,
                'title'      => '分类管理',
                'icon'       => null,
                'uri'        => 'article_category',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-30 08:07:43',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            12 => [
                'id'         => 14,
                'parent_id'  => 0,
                'order'      => 4,
                'title'      => '用户中心',
                'icon'       => 'fa-user-circle-o',
                'uri'        => null,
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-30 09:17:19',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            13 => [
                'id'         => 15,
                'parent_id'  => 14,
                'order'      => 5,
                'title'      => '用户管理',
                'icon'       => null,
                'uri'        => 'user',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-06-30 09:18:01',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            18 => [
                'id'         => 26,
                'parent_id'  => 14,
                'order'      => 6,
                'title'      => '账户管理',
                'icon'       => null,
                'uri'        => 'account',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-07-06 02:42:48',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            19 => [
                'id'         => 27,
                'parent_id'  => 0,
                'order'      => 11,
                'title'      => '社区中心',
                'icon'       => 'fa-camera',
                'uri'        => null,
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-07-11 21:33:12',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            20 => [
                'id'         => 28,
                'parent_id'  => 27,
                'order'      => 14,
                'title'      => '话题管理',
                'icon'       => null,
                'uri'        => 'feed_topic',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-07-11 21:33:57',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            21 => [
                'id'         => 29,
                'parent_id'  => 27,
                'order'      => 12,
                'title'      => '动态管理',
                'icon'       => null,
                'uri'        => 'feed',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-07-11 21:35:23',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            22 => [
                'id'         => 30,
                'parent_id'  => 27,
                'order'      => 15,
                'title'      => '评论管理',
                'icon'       => null,
                'uri'        => 'comments',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-07-11 21:35:46',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            28 => [
                'id'         => 37,
                'parent_id'  => 2,
                'order'      => 37,
                'title'      => '队列管理',
                'icon'       => null,
                'uri'        => 'horizon',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-11-27 16:37:24',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            29 => [
                'id'         => 38,
                'parent_id'  => 14,
                'order'      => 7,
                'title'      => '系统通知',
                'icon'       => null,
                'uri'        => 'notifications',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2020-12-03 13:45:55',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            30 => [
                'id'         => 39,
                'parent_id'  => 0,
                'order'      => 8,
                'title'      => '消息中心',
                'icon'       => 'fa-commenting',
                'uri'        => null,
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2021-03-09 13:56:34',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            31 => [
                'id'         => 40,
                'parent_id'  => 39,
                'order'      => 9,
                'title'      => '对话管理',
                'icon'       => null,
                'uri'        => 'conversations',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2021-03-09 14:00:06',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            32 => [
                'id'         => 41,
                'parent_id'  => 39,
                'order'      => 10,
                'title'      => '消息管理',
                'icon'       => null,
                'uri'        => 'messages',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2021-03-09 14:00:37',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            33 => [
                'id'         => 42,
                'parent_id'  => 0,
                'order'      => 2,
                'title'      => '审核中心',
                'icon'       => 'fa-lock',
                'uri'        => null,
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2021-05-20 13:01:12',
                'updated_at' => '2021-05-20 13:02:01',
            ],
            34 => [
                'id'         => 43,
                'parent_id'  => 42,
                'order'      => 3,
                'title'      => '动态审核',
                'icon'       => null,
                'uri'        => 'feed_audit',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2021-05-25 11:33:29',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            35 => [
                'id'         => 44,
                'parent_id'  => 12,
                'order'      => 18,
                'title'      => '文章管理',
                'icon'       => null,
                'uri'        => 'article',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2022-04-20 21:24:53',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            36 => [
                'id'         => 45,
                'parent_id'  => 27,
                'order'      => 13,
                'title'      => '话题分组',
                'icon'       => null,
                'uri'        => 'topic_group',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2022-04-24 20:13:34',
                'updated_at' => '2022-04-24 20:13:46',
            ],
            37 => [
                'id'         => 46,
                'parent_id'  => 2,
                'order'      => 38,
                'title'      => '定时任务管理',
                'icon'       => null,
                'uri'        => 'totem',
                'extension'  => '',
                'show'       => 1,
                'created_at' => '2023-03-17 14:44:27',
                'updated_at' => '2023-03-17 14:44:27',
            ],
        ]);
    }
}
